services:
  isza-screenshots:
    container_name: isza
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${VAR_DIR:-./var}:/app/var
      - ./instagram:/app/instagram
    # networks:
    #   - site_network
    env_file:
      - .env
    environment:
      - ISZA_VAR_DIR=/app/var
      - ISZA_INSTA_WORKING_DIR=/app/instagram
    command: ./app --port 8000
    ports:
      - "8000:8000"

# networks:
#   site_network:
#     external: true
